name: Deploy
 

on:

  
push:

    
branches:

      
-
 
main

jobs:

  
build:

    
name:
 
Build

    
runs-on:
 
ubuntu-latest

    
steps:

      
-
 
uses:
 
actions/checkout@v2

      
-
 
name:
 
Install
 
dependencies

        
run:
 
npm
 
install

      
-
 
name:
 
Build

        
run: npm run build
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Create gh-pages branch
        run: git checkout -b gh-pages
      - name: Copy built files to gh-pages branch
        run: cp -r dist/* .
      - name: Push gh-pages branch
        run: git add -A
        run: git commit -m 'Deploy to GitHub Pages'
        run: git push origin gh-pages
